//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.PagoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="PagoWS.Pago")]
    public interface Pago {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/eliminarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/eliminarPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.PagoWS.eliminarPagoResponse eliminarPago(SoftGestWA.PagoWS.eliminarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/eliminarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/eliminarPagoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.eliminarPagoResponse> eliminarPagoAsync(SoftGestWA.PagoWS.eliminarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/modificarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/modificarPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.PagoWS.modificarPagoResponse modificarPago(SoftGestWA.PagoWS.modificarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/modificarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/modificarPagoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.modificarPagoResponse> modificarPagoAsync(SoftGestWA.PagoWS.modificarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/obtenerPorIdPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/obtenerPorIdPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.PagoWS.obtenerPorIdPagoResponse obtenerPorIdPago(SoftGestWA.PagoWS.obtenerPorIdPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/obtenerPorIdPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/obtenerPorIdPagoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.obtenerPorIdPagoResponse> obtenerPorIdPagoAsync(SoftGestWA.PagoWS.obtenerPorIdPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/insertarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/insertarPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.PagoWS.insertarPagoResponse insertarPago(SoftGestWA.PagoWS.insertarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/insertarPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/insertarPagoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.insertarPagoResponse> insertarPagoAsync(SoftGestWA.PagoWS.insertarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/listarTodosPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/listarTodosPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.PagoWS.listarTodosPagoResponse listarTodosPago(SoftGestWA.PagoWS.listarTodosPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Pago/listarTodosPagoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Pago/listarTodosPagoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.listarTodosPagoResponse> listarTodosPagoAsync(SoftGestWA.PagoWS.listarTodosPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPago", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPago;
        
        public eliminarPagoRequest() {
        }
        
        public eliminarPagoRequest(int idPago) {
            this.idPago = idPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPagoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPagoResponse() {
        }
        
        public eliminarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPago", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFkCita;
        
        public modificarPagoRequest() {
        }
        
        public modificarPagoRequest(int idPago, string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            this.idPago = idPago;
            this.tipo = tipo;
            this.estado = estado;
            this.dia = dia;
            this.mes = mes;
            this.anio = anio;
            this.idFkCita = idFkCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPagoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPagoResponse() {
        }
        
        public modificarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class pagoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private citaDTO citaDTOField;
        
        private estadoPago estadoField;
        
        private bool estadoFieldSpecified;
        
        private localDate fechaField;
        
        private int idPagoField;
        
        private bool idPagoFieldSpecified;
        
        private tipoPago tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public citaDTO citaDTO {
            get {
                return this.citaDTOField;
            }
            set {
                this.citaDTOField = value;
                this.RaisePropertyChanged("citaDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPago estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPago {
            get {
                return this.idPagoField;
            }
            set {
                this.idPagoField = value;
                this.RaisePropertyChanged("idPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPagoSpecified {
            get {
                return this.idPagoFieldSpecified;
            }
            set {
                this.idPagoFieldSpecified = value;
                this.RaisePropertyChanged("idPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoPago tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class citaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private asistenteMostradorDTO asistenteMostradorDTOField;
        
        private time duracionField;
        
        private estadoCita estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private time horaField;
        
        private int idCitaField;
        
        private bool idCitaFieldSpecified;
        
        private jefeOdontologicoDTO jefeOdontologicoDTOField;
        
        private string observacionField;
        
        private odontologoDTO odontologoDTOField;
        
        private pacienteDTO pacienteDTOField;
        
        private tratamientoDTO tratamientoDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public asistenteMostradorDTO asistenteMostradorDTO {
            get {
                return this.asistenteMostradorDTOField;
            }
            set {
                this.asistenteMostradorDTOField = value;
                this.RaisePropertyChanged("asistenteMostradorDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public time duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoCita estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public time hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCitaSpecified {
            get {
                return this.idCitaFieldSpecified;
            }
            set {
                this.idCitaFieldSpecified = value;
                this.RaisePropertyChanged("idCitaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public jefeOdontologicoDTO jefeOdontologicoDTO {
            get {
                return this.jefeOdontologicoDTOField;
            }
            set {
                this.jefeOdontologicoDTOField = value;
                this.RaisePropertyChanged("jefeOdontologicoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public odontologoDTO odontologoDTO {
            get {
                return this.odontologoDTOField;
            }
            set {
                this.odontologoDTOField = value;
                this.RaisePropertyChanged("odontologoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public pacienteDTO pacienteDTO {
            get {
                return this.pacienteDTOField;
            }
            set {
                this.pacienteDTOField = value;
                this.RaisePropertyChanged("pacienteDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public tratamientoDTO tratamientoDTO {
            get {
                return this.tratamientoDTOField;
            }
            set {
                this.tratamientoDTOField = value;
                this.RaisePropertyChanged("tratamientoDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class asistenteMostradorDTO : usuarioDTO {
        
        private disponibilidad estadoField;
        
        private bool estadoFieldSpecified;
        
        private turno turnoField;
        
        private bool turnoFieldSpecified;
        
        private turnoPersonalDTO turnoPersonalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public disponibilidad estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public turno turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public turnoPersonalDTO turnoPersonal {
            get {
                return this.turnoPersonalField;
            }
            set {
                this.turnoPersonalField = value;
                this.RaisePropertyChanged("turnoPersonal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum disponibilidad {
        
        /// <remarks/>
        Disponible,
        
        /// <remarks/>
        NoDisponible,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum turno {
        
        /// <remarks/>
        Mañana,
        
        /// <remarks/>
        Tarde,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class turnoPersonalDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private disponibilidad estadoField;
        
        private bool estadoFieldSpecified;
        
        private int idTurnoPersonalField;
        
        private bool idTurnoPersonalFieldSpecified;
        
        private turno turnoField;
        
        private bool turnoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public disponibilidad estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTurnoPersonal {
            get {
                return this.idTurnoPersonalField;
            }
            set {
                this.idTurnoPersonalField = value;
                this.RaisePropertyChanged("idTurnoPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTurnoPersonalSpecified {
            get {
                return this.idTurnoPersonalFieldSpecified;
            }
            set {
                this.idTurnoPersonalFieldSpecified = value;
                this.RaisePropertyChanged("idTurnoPersonalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public turno turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoTratamientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoTratamientoField;
        
        private bool idTipoTratamientoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoTratamiento {
            get {
                return this.idTipoTratamientoField;
            }
            set {
                this.idTipoTratamientoField = value;
                this.RaisePropertyChanged("idTipoTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoTratamientoSpecified {
            get {
                return this.idTipoTratamientoFieldSpecified;
            }
            set {
                this.idTipoTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tratamientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private bool costoFieldSpecified;
        
        private int idTratamientoField;
        
        private bool idTratamientoFieldSpecified;
        
        private string nombreField;
        
        private tipoTratamientoDTO tipoTratamientoDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoSpecified {
            get {
                return this.costoFieldSpecified;
            }
            set {
                this.costoFieldSpecified = value;
                this.RaisePropertyChanged("costoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTratamientoSpecified {
            get {
                return this.idTratamientoFieldSpecified;
            }
            set {
                this.idTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoTratamientoDTO tipoTratamientoDTO {
            get {
                return this.tipoTratamientoDTOField;
            }
            set {
                this.tipoTratamientoDTOField = value;
                this.RaisePropertyChanged("tipoTratamientoDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class time : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pacienteDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(odontologoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jefeOdontologicoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(asistenteMostradorDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombresField;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        Masculino,
        
        /// <remarks/>
        Femenino,
        
        /// <remarks/>
        OTRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class pacienteDTO : usuarioDTO {
        
        private System.Nullable<alergia>[] alergiasField;
        
        private string condicionesPreviasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alergias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<alergia>[] alergias {
            get {
                return this.alergiasField;
            }
            set {
                this.alergiasField = value;
                this.RaisePropertyChanged("alergias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string condicionesPrevias {
            get {
                return this.condicionesPreviasField;
            }
            set {
                this.condicionesPreviasField = value;
                this.RaisePropertyChanged("condicionesPrevias");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum alergia {
        
        /// <remarks/>
        Antibioticos,
        
        /// <remarks/>
        Analgesicos,
        
        /// <remarks/>
        Latex,
        
        /// <remarks/>
        Sulfamidas,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class odontologoDTO : usuarioDTO {
        
        private especialidad especialidadField;
        
        private bool especialidadFieldSpecified;
        
        private disponibilidad estadoField;
        
        private bool estadoFieldSpecified;
        
        private turno turnoField;
        
        private bool turnoFieldSpecified;
        
        private turnoPersonalDTO turnoPersonalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool especialidadSpecified {
            get {
                return this.especialidadFieldSpecified;
            }
            set {
                this.especialidadFieldSpecified = value;
                this.RaisePropertyChanged("especialidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public disponibilidad estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public turno turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public turnoPersonalDTO turnoPersonal {
            get {
                return this.turnoPersonalField;
            }
            set {
                this.turnoPersonalField = value;
                this.RaisePropertyChanged("turnoPersonal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum especialidad {
        
        /// <remarks/>
        Ortodoncia,
        
        /// <remarks/>
        Endodoncia,
        
        /// <remarks/>
        Peridoncia,
        
        /// <remarks/>
        Implantologia,
        
        /// <remarks/>
        Radiologia,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class jefeOdontologicoDTO : usuarioDTO {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum estadoCita {
        
        /// <remarks/>
        EnTiempo,
        
        /// <remarks/>
        Finalizado,
        
        /// <remarks/>
        EnProceso,
        
        /// <remarks/>
        Reprogramado,
        
        /// <remarks/>
        Cancelado,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum estadoPago {
        
        /// <remarks/>
        Pagado,
        
        /// <remarks/>
        Falta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum tipoPago {
        
        /// <remarks/>
        Efectivo,
        
        /// <remarks/>
        Transferencia,
        
        /// <remarks/>
        Tarjeta,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPago", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPago;
        
        public obtenerPorIdPagoRequest() {
        }
        
        public obtenerPorIdPagoRequest(int idPago) {
            this.idPago = idPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPagoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.PagoWS.pagoDTO @return;
        
        public obtenerPorIdPagoResponse() {
        }
        
        public obtenerPorIdPagoResponse(SoftGestWA.PagoWS.pagoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPago", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFkCita;
        
        public insertarPagoRequest() {
        }
        
        public insertarPagoRequest(string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            this.tipo = tipo;
            this.estado = estado;
            this.dia = dia;
            this.mes = mes;
            this.anio = anio;
            this.idFkCita = idFkCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPagoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPagoResponse() {
        }
        
        public insertarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPago", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPagoRequest {
        
        public listarTodosPagoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPagoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.PagoWS.pagoDTO[] @return;
        
        public listarTodosPagoResponse() {
        }
        
        public listarTodosPagoResponse(SoftGestWA.PagoWS.pagoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagoChannel : SoftGestWA.PagoWS.Pago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoClient : System.ServiceModel.ClientBase<SoftGestWA.PagoWS.Pago>, SoftGestWA.PagoWS.Pago {
        
        public PagoClient() {
        }
        
        public PagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.PagoWS.eliminarPagoResponse SoftGestWA.PagoWS.Pago.eliminarPago(SoftGestWA.PagoWS.eliminarPagoRequest request) {
            return base.Channel.eliminarPago(request);
        }
        
        public int eliminarPago(int idPago) {
            SoftGestWA.PagoWS.eliminarPagoRequest inValue = new SoftGestWA.PagoWS.eliminarPagoRequest();
            inValue.idPago = idPago;
            SoftGestWA.PagoWS.eliminarPagoResponse retVal = ((SoftGestWA.PagoWS.Pago)(this)).eliminarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.eliminarPagoResponse> SoftGestWA.PagoWS.Pago.eliminarPagoAsync(SoftGestWA.PagoWS.eliminarPagoRequest request) {
            return base.Channel.eliminarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.PagoWS.eliminarPagoResponse> eliminarPagoAsync(int idPago) {
            SoftGestWA.PagoWS.eliminarPagoRequest inValue = new SoftGestWA.PagoWS.eliminarPagoRequest();
            inValue.idPago = idPago;
            return ((SoftGestWA.PagoWS.Pago)(this)).eliminarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.PagoWS.modificarPagoResponse SoftGestWA.PagoWS.Pago.modificarPago(SoftGestWA.PagoWS.modificarPagoRequest request) {
            return base.Channel.modificarPago(request);
        }
        
        public int modificarPago(int idPago, string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            SoftGestWA.PagoWS.modificarPagoRequest inValue = new SoftGestWA.PagoWS.modificarPagoRequest();
            inValue.idPago = idPago;
            inValue.tipo = tipo;
            inValue.estado = estado;
            inValue.dia = dia;
            inValue.mes = mes;
            inValue.anio = anio;
            inValue.idFkCita = idFkCita;
            SoftGestWA.PagoWS.modificarPagoResponse retVal = ((SoftGestWA.PagoWS.Pago)(this)).modificarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.modificarPagoResponse> SoftGestWA.PagoWS.Pago.modificarPagoAsync(SoftGestWA.PagoWS.modificarPagoRequest request) {
            return base.Channel.modificarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.PagoWS.modificarPagoResponse> modificarPagoAsync(int idPago, string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            SoftGestWA.PagoWS.modificarPagoRequest inValue = new SoftGestWA.PagoWS.modificarPagoRequest();
            inValue.idPago = idPago;
            inValue.tipo = tipo;
            inValue.estado = estado;
            inValue.dia = dia;
            inValue.mes = mes;
            inValue.anio = anio;
            inValue.idFkCita = idFkCita;
            return ((SoftGestWA.PagoWS.Pago)(this)).modificarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.PagoWS.obtenerPorIdPagoResponse SoftGestWA.PagoWS.Pago.obtenerPorIdPago(SoftGestWA.PagoWS.obtenerPorIdPagoRequest request) {
            return base.Channel.obtenerPorIdPago(request);
        }
        
        public SoftGestWA.PagoWS.pagoDTO obtenerPorIdPago(int idPago) {
            SoftGestWA.PagoWS.obtenerPorIdPagoRequest inValue = new SoftGestWA.PagoWS.obtenerPorIdPagoRequest();
            inValue.idPago = idPago;
            SoftGestWA.PagoWS.obtenerPorIdPagoResponse retVal = ((SoftGestWA.PagoWS.Pago)(this)).obtenerPorIdPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.obtenerPorIdPagoResponse> SoftGestWA.PagoWS.Pago.obtenerPorIdPagoAsync(SoftGestWA.PagoWS.obtenerPorIdPagoRequest request) {
            return base.Channel.obtenerPorIdPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.PagoWS.obtenerPorIdPagoResponse> obtenerPorIdPagoAsync(int idPago) {
            SoftGestWA.PagoWS.obtenerPorIdPagoRequest inValue = new SoftGestWA.PagoWS.obtenerPorIdPagoRequest();
            inValue.idPago = idPago;
            return ((SoftGestWA.PagoWS.Pago)(this)).obtenerPorIdPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.PagoWS.insertarPagoResponse SoftGestWA.PagoWS.Pago.insertarPago(SoftGestWA.PagoWS.insertarPagoRequest request) {
            return base.Channel.insertarPago(request);
        }
        
        public int insertarPago(string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            SoftGestWA.PagoWS.insertarPagoRequest inValue = new SoftGestWA.PagoWS.insertarPagoRequest();
            inValue.tipo = tipo;
            inValue.estado = estado;
            inValue.dia = dia;
            inValue.mes = mes;
            inValue.anio = anio;
            inValue.idFkCita = idFkCita;
            SoftGestWA.PagoWS.insertarPagoResponse retVal = ((SoftGestWA.PagoWS.Pago)(this)).insertarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.insertarPagoResponse> SoftGestWA.PagoWS.Pago.insertarPagoAsync(SoftGestWA.PagoWS.insertarPagoRequest request) {
            return base.Channel.insertarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.PagoWS.insertarPagoResponse> insertarPagoAsync(string tipo, string estado, int dia, int mes, int anio, int idFkCita) {
            SoftGestWA.PagoWS.insertarPagoRequest inValue = new SoftGestWA.PagoWS.insertarPagoRequest();
            inValue.tipo = tipo;
            inValue.estado = estado;
            inValue.dia = dia;
            inValue.mes = mes;
            inValue.anio = anio;
            inValue.idFkCita = idFkCita;
            return ((SoftGestWA.PagoWS.Pago)(this)).insertarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.PagoWS.listarTodosPagoResponse SoftGestWA.PagoWS.Pago.listarTodosPago(SoftGestWA.PagoWS.listarTodosPagoRequest request) {
            return base.Channel.listarTodosPago(request);
        }
        
        public SoftGestWA.PagoWS.pagoDTO[] listarTodosPago() {
            SoftGestWA.PagoWS.listarTodosPagoRequest inValue = new SoftGestWA.PagoWS.listarTodosPagoRequest();
            SoftGestWA.PagoWS.listarTodosPagoResponse retVal = ((SoftGestWA.PagoWS.Pago)(this)).listarTodosPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.PagoWS.listarTodosPagoResponse> SoftGestWA.PagoWS.Pago.listarTodosPagoAsync(SoftGestWA.PagoWS.listarTodosPagoRequest request) {
            return base.Channel.listarTodosPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.PagoWS.listarTodosPagoResponse> listarTodosPagoAsync() {
            SoftGestWA.PagoWS.listarTodosPagoRequest inValue = new SoftGestWA.PagoWS.listarTodosPagoRequest();
            return ((SoftGestWA.PagoWS.Pago)(this)).listarTodosPagoAsync(inValue);
        }
    }
}
