//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.TipoMaquinaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="TipoMaquinaWS.TipoMaquina")]
    public interface TipoMaquina {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/insertarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/insertarTipoMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse insertarTipoMaquina(SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/insertarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/insertarTipoMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse> insertarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/modificarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/modificarTipoMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse modificarTipoMaquina(SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/modificarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/modificarTipoMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse> modificarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/obtenerPorIdTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/obtenerPorIdTipoMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse obtenerPorIdTipoMaquina(SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/obtenerPorIdTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/obtenerPorIdTipoMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse> obtenerPorIdTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/listarTodosTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/listarTodosTipoMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse listarTodosTipoMaquina(SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/listarTodosTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/listarTodosTipoMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse> listarTodosTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/eliminarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/eliminarTipoMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse eliminarTipoMaquina(SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoMaquina/eliminarTipoMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoMaquina/eliminarTipoMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse> eliminarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public insertarTipoMaquinaRequest() {
        }
        
        public insertarTipoMaquinaRequest(string nombre, string descripcion) {
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoMaquinaResponse() {
        }
        
        public insertarTipoMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public modificarTipoMaquinaRequest() {
        }
        
        public modificarTipoMaquinaRequest(int idTipoMaquina, string nombre, string descripcion) {
            this.idTipoMaquina = idTipoMaquina;
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTipoMaquinaResponse() {
        }
        
        public modificarTipoMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoMaquinaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoMaquinasField;
        
        private bool idTipoMaquinasFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoMaquinas {
            get {
                return this.idTipoMaquinasField;
            }
            set {
                this.idTipoMaquinasField = value;
                this.RaisePropertyChanged("idTipoMaquinas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMaquinasSpecified {
            get {
                return this.idTipoMaquinasFieldSpecified;
            }
            set {
                this.idTipoMaquinasFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMaquinasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaquina;
        
        public obtenerPorIdTipoMaquinaRequest() {
        }
        
        public obtenerPorIdTipoMaquinaRequest(int idTipoMaquina) {
            this.idTipoMaquina = idTipoMaquina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO @return;
        
        public obtenerPorIdTipoMaquinaResponse() {
        }
        
        public obtenerPorIdTipoMaquinaResponse(SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoMaquinaRequest {
        
        public listarTodosTipoMaquinaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO[] @return;
        
        public listarTodosTipoMaquinaResponse() {
        }
        
        public listarTodosTipoMaquinaResponse(SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaquina;
        
        public eliminarTipoMaquinaRequest() {
        }
        
        public eliminarTipoMaquinaRequest(int idTipoMaquina) {
            this.idTipoMaquina = idTipoMaquina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTipoMaquinaResponse() {
        }
        
        public eliminarTipoMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoMaquinaChannel : SoftGestWA.TipoMaquinaWS.TipoMaquina, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoMaquinaClient : System.ServiceModel.ClientBase<SoftGestWA.TipoMaquinaWS.TipoMaquina>, SoftGestWA.TipoMaquinaWS.TipoMaquina {
        
        public TipoMaquinaClient() {
        }
        
        public TipoMaquinaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoMaquinaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoMaquinaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoMaquinaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse SoftGestWA.TipoMaquinaWS.TipoMaquina.insertarTipoMaquina(SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest request) {
            return base.Channel.insertarTipoMaquina(request);
        }
        
        public int insertarTipoMaquina(string nombre, string descripcion) {
            SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse retVal = ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).insertarTipoMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse> SoftGestWA.TipoMaquinaWS.TipoMaquina.insertarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest request) {
            return base.Channel.insertarTipoMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaResponse> insertarTipoMaquinaAsync(string nombre, string descripcion) {
            SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.insertarTipoMaquinaRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).insertarTipoMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse SoftGestWA.TipoMaquinaWS.TipoMaquina.modificarTipoMaquina(SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest request) {
            return base.Channel.modificarTipoMaquina(request);
        }
        
        public int modificarTipoMaquina(int idTipoMaquina, string nombre, string descripcion) {
            SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse retVal = ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).modificarTipoMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse> SoftGestWA.TipoMaquinaWS.TipoMaquina.modificarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest request) {
            return base.Channel.modificarTipoMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaResponse> modificarTipoMaquinaAsync(int idTipoMaquina, string nombre, string descripcion) {
            SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.modificarTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).modificarTipoMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse SoftGestWA.TipoMaquinaWS.TipoMaquina.obtenerPorIdTipoMaquina(SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest request) {
            return base.Channel.obtenerPorIdTipoMaquina(request);
        }
        
        public SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO obtenerPorIdTipoMaquina(int idTipoMaquina) {
            SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse retVal = ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).obtenerPorIdTipoMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse> SoftGestWA.TipoMaquinaWS.TipoMaquina.obtenerPorIdTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest request) {
            return base.Channel.obtenerPorIdTipoMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaResponse> obtenerPorIdTipoMaquinaAsync(int idTipoMaquina) {
            SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.obtenerPorIdTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            return ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).obtenerPorIdTipoMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse SoftGestWA.TipoMaquinaWS.TipoMaquina.listarTodosTipoMaquina(SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest request) {
            return base.Channel.listarTodosTipoMaquina(request);
        }
        
        public SoftGestWA.TipoMaquinaWS.tipoMaquinaDTO[] listarTodosTipoMaquina() {
            SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest();
            SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse retVal = ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).listarTodosTipoMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse> SoftGestWA.TipoMaquinaWS.TipoMaquina.listarTodosTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest request) {
            return base.Channel.listarTodosTipoMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaResponse> listarTodosTipoMaquinaAsync() {
            SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.listarTodosTipoMaquinaRequest();
            return ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).listarTodosTipoMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse SoftGestWA.TipoMaquinaWS.TipoMaquina.eliminarTipoMaquina(SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest request) {
            return base.Channel.eliminarTipoMaquina(request);
        }
        
        public int eliminarTipoMaquina(int idTipoMaquina) {
            SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse retVal = ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).eliminarTipoMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse> SoftGestWA.TipoMaquinaWS.TipoMaquina.eliminarTipoMaquinaAsync(SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest request) {
            return base.Channel.eliminarTipoMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaResponse> eliminarTipoMaquinaAsync(int idTipoMaquina) {
            SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest inValue = new SoftGestWA.TipoMaquinaWS.eliminarTipoMaquinaRequest();
            inValue.idTipoMaquina = idTipoMaquina;
            return ((SoftGestWA.TipoMaquinaWS.TipoMaquina)(this)).eliminarTipoMaquinaAsync(inValue);
        }
    }
}
