//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.TratamientoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="TratamientoWS.Tratamiento")]
    public interface Tratamiento {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/modificarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/modificarTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TratamientoWS.modificarTratamientoResponse modificarTratamiento(SoftGestWA.TratamientoWS.modificarTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/modificarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/modificarTratamientoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.modificarTratamientoResponse> modificarTratamientoAsync(SoftGestWA.TratamientoWS.modificarTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/insertarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/insertarTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TratamientoWS.insertarTratamientoResponse insertarTratamiento(SoftGestWA.TratamientoWS.insertarTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/insertarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/insertarTratamientoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.insertarTratamientoResponse> insertarTratamientoAsync(SoftGestWA.TratamientoWS.insertarTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/obtenerPorIdTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/obtenerPorIdTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse obtenerPorIdTratamiento(SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/obtenerPorIdTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/obtenerPorIdTratamientoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse> obtenerPorIdTratamientoAsync(SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/eliminarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/eliminarTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TratamientoWS.eliminarTratamientoResponse eliminarTratamiento(SoftGestWA.TratamientoWS.eliminarTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/eliminarTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/eliminarTratamientoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.eliminarTratamientoResponse> eliminarTratamientoAsync(SoftGestWA.TratamientoWS.eliminarTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/listarTodosTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/listarTodosTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TratamientoWS.listarTodosTratamientoResponse listarTodosTratamiento(SoftGestWA.TratamientoWS.listarTodosTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Tratamiento/listarTodosTratamientoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Tratamiento/listarTodosTratamientoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.listarTodosTratamientoResponse> listarTodosTratamientoAsync(SoftGestWA.TratamientoWS.listarTodosTratamientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTratamiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double costo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFkTipoTratamiento;
        
        public modificarTratamientoRequest() {
        }
        
        public modificarTratamientoRequest(int idTratamiento, string nombre, double costo, int idFkTipoTratamiento) {
            this.idTratamiento = idTratamiento;
            this.nombre = nombre;
            this.costo = costo;
            this.idFkTipoTratamiento = idFkTipoTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTratamientoResponse() {
        }
        
        public modificarTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double costo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFkTipoTratamiento;
        
        public insertarTratamientoRequest() {
        }
        
        public insertarTratamientoRequest(string nombre, double costo, int idFkTipoTratamiento) {
            this.nombre = nombre;
            this.costo = costo;
            this.idFkTipoTratamiento = idFkTipoTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTratamientoResponse() {
        }
        
        public insertarTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tratamientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double costoField;
        
        private bool costoFieldSpecified;
        
        private int idTratamientoField;
        
        private bool idTratamientoFieldSpecified;
        
        private string nombreField;
        
        private tipoTratamientoDTO tipoTratamientoDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoSpecified {
            get {
                return this.costoFieldSpecified;
            }
            set {
                this.costoFieldSpecified = value;
                this.RaisePropertyChanged("costoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTratamiento {
            get {
                return this.idTratamientoField;
            }
            set {
                this.idTratamientoField = value;
                this.RaisePropertyChanged("idTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTratamientoSpecified {
            get {
                return this.idTratamientoFieldSpecified;
            }
            set {
                this.idTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoTratamientoDTO tipoTratamientoDTO {
            get {
                return this.tipoTratamientoDTOField;
            }
            set {
                this.tipoTratamientoDTOField = value;
                this.RaisePropertyChanged("tipoTratamientoDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoTratamientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoTratamientoField;
        
        private bool idTipoTratamientoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoTratamiento {
            get {
                return this.idTipoTratamientoField;
            }
            set {
                this.idTipoTratamientoField = value;
                this.RaisePropertyChanged("idTipoTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoTratamientoSpecified {
            get {
                return this.idTipoTratamientoFieldSpecified;
            }
            set {
                this.idTipoTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTratamiento;
        
        public obtenerPorIdTratamientoRequest() {
        }
        
        public obtenerPorIdTratamientoRequest(int idTratamiento) {
            this.idTratamiento = idTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TratamientoWS.tratamientoDTO @return;
        
        public obtenerPorIdTratamientoResponse() {
        }
        
        public obtenerPorIdTratamientoResponse(SoftGestWA.TratamientoWS.tratamientoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTratamiento;
        
        public eliminarTratamientoRequest() {
        }
        
        public eliminarTratamientoRequest(int idTratamiento) {
            this.idTratamiento = idTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTratamientoResponse() {
        }
        
        public eliminarTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTratamientoRequest {
        
        public listarTodosTratamientoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TratamientoWS.tratamientoDTO[] @return;
        
        public listarTodosTratamientoResponse() {
        }
        
        public listarTodosTratamientoResponse(SoftGestWA.TratamientoWS.tratamientoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TratamientoChannel : SoftGestWA.TratamientoWS.Tratamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TratamientoClient : System.ServiceModel.ClientBase<SoftGestWA.TratamientoWS.Tratamiento>, SoftGestWA.TratamientoWS.Tratamiento {
        
        public TratamientoClient() {
        }
        
        public TratamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TratamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TratamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TratamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TratamientoWS.modificarTratamientoResponse SoftGestWA.TratamientoWS.Tratamiento.modificarTratamiento(SoftGestWA.TratamientoWS.modificarTratamientoRequest request) {
            return base.Channel.modificarTratamiento(request);
        }
        
        public int modificarTratamiento(int idTratamiento, string nombre, double costo, int idFkTipoTratamiento) {
            SoftGestWA.TratamientoWS.modificarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.modificarTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            inValue.nombre = nombre;
            inValue.costo = costo;
            inValue.idFkTipoTratamiento = idFkTipoTratamiento;
            SoftGestWA.TratamientoWS.modificarTratamientoResponse retVal = ((SoftGestWA.TratamientoWS.Tratamiento)(this)).modificarTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.modificarTratamientoResponse> SoftGestWA.TratamientoWS.Tratamiento.modificarTratamientoAsync(SoftGestWA.TratamientoWS.modificarTratamientoRequest request) {
            return base.Channel.modificarTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.modificarTratamientoResponse> modificarTratamientoAsync(int idTratamiento, string nombre, double costo, int idFkTipoTratamiento) {
            SoftGestWA.TratamientoWS.modificarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.modificarTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            inValue.nombre = nombre;
            inValue.costo = costo;
            inValue.idFkTipoTratamiento = idFkTipoTratamiento;
            return ((SoftGestWA.TratamientoWS.Tratamiento)(this)).modificarTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TratamientoWS.insertarTratamientoResponse SoftGestWA.TratamientoWS.Tratamiento.insertarTratamiento(SoftGestWA.TratamientoWS.insertarTratamientoRequest request) {
            return base.Channel.insertarTratamiento(request);
        }
        
        public int insertarTratamiento(string nombre, double costo, int idFkTipoTratamiento) {
            SoftGestWA.TratamientoWS.insertarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.insertarTratamientoRequest();
            inValue.nombre = nombre;
            inValue.costo = costo;
            inValue.idFkTipoTratamiento = idFkTipoTratamiento;
            SoftGestWA.TratamientoWS.insertarTratamientoResponse retVal = ((SoftGestWA.TratamientoWS.Tratamiento)(this)).insertarTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.insertarTratamientoResponse> SoftGestWA.TratamientoWS.Tratamiento.insertarTratamientoAsync(SoftGestWA.TratamientoWS.insertarTratamientoRequest request) {
            return base.Channel.insertarTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.insertarTratamientoResponse> insertarTratamientoAsync(string nombre, double costo, int idFkTipoTratamiento) {
            SoftGestWA.TratamientoWS.insertarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.insertarTratamientoRequest();
            inValue.nombre = nombre;
            inValue.costo = costo;
            inValue.idFkTipoTratamiento = idFkTipoTratamiento;
            return ((SoftGestWA.TratamientoWS.Tratamiento)(this)).insertarTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse SoftGestWA.TratamientoWS.Tratamiento.obtenerPorIdTratamiento(SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest request) {
            return base.Channel.obtenerPorIdTratamiento(request);
        }
        
        public SoftGestWA.TratamientoWS.tratamientoDTO obtenerPorIdTratamiento(int idTratamiento) {
            SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest inValue = new SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse retVal = ((SoftGestWA.TratamientoWS.Tratamiento)(this)).obtenerPorIdTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse> SoftGestWA.TratamientoWS.Tratamiento.obtenerPorIdTratamientoAsync(SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest request) {
            return base.Channel.obtenerPorIdTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.obtenerPorIdTratamientoResponse> obtenerPorIdTratamientoAsync(int idTratamiento) {
            SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest inValue = new SoftGestWA.TratamientoWS.obtenerPorIdTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            return ((SoftGestWA.TratamientoWS.Tratamiento)(this)).obtenerPorIdTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TratamientoWS.eliminarTratamientoResponse SoftGestWA.TratamientoWS.Tratamiento.eliminarTratamiento(SoftGestWA.TratamientoWS.eliminarTratamientoRequest request) {
            return base.Channel.eliminarTratamiento(request);
        }
        
        public int eliminarTratamiento(int idTratamiento) {
            SoftGestWA.TratamientoWS.eliminarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.eliminarTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            SoftGestWA.TratamientoWS.eliminarTratamientoResponse retVal = ((SoftGestWA.TratamientoWS.Tratamiento)(this)).eliminarTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.eliminarTratamientoResponse> SoftGestWA.TratamientoWS.Tratamiento.eliminarTratamientoAsync(SoftGestWA.TratamientoWS.eliminarTratamientoRequest request) {
            return base.Channel.eliminarTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.eliminarTratamientoResponse> eliminarTratamientoAsync(int idTratamiento) {
            SoftGestWA.TratamientoWS.eliminarTratamientoRequest inValue = new SoftGestWA.TratamientoWS.eliminarTratamientoRequest();
            inValue.idTratamiento = idTratamiento;
            return ((SoftGestWA.TratamientoWS.Tratamiento)(this)).eliminarTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TratamientoWS.listarTodosTratamientoResponse SoftGestWA.TratamientoWS.Tratamiento.listarTodosTratamiento(SoftGestWA.TratamientoWS.listarTodosTratamientoRequest request) {
            return base.Channel.listarTodosTratamiento(request);
        }
        
        public SoftGestWA.TratamientoWS.tratamientoDTO[] listarTodosTratamiento() {
            SoftGestWA.TratamientoWS.listarTodosTratamientoRequest inValue = new SoftGestWA.TratamientoWS.listarTodosTratamientoRequest();
            SoftGestWA.TratamientoWS.listarTodosTratamientoResponse retVal = ((SoftGestWA.TratamientoWS.Tratamiento)(this)).listarTodosTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.listarTodosTratamientoResponse> SoftGestWA.TratamientoWS.Tratamiento.listarTodosTratamientoAsync(SoftGestWA.TratamientoWS.listarTodosTratamientoRequest request) {
            return base.Channel.listarTodosTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TratamientoWS.listarTodosTratamientoResponse> listarTodosTratamientoAsync() {
            SoftGestWA.TratamientoWS.listarTodosTratamientoRequest inValue = new SoftGestWA.TratamientoWS.listarTodosTratamientoRequest();
            return ((SoftGestWA.TratamientoWS.Tratamiento)(this)).listarTodosTratamientoAsync(inValue);
        }
    }
}
