//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.TipoTratamientoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="TipoTratamientoWS.TipoTratamiento")]
    public interface TipoTratamiento {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/obtenerPorIdTipoTratamientoR" +
            "equest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/obtenerPorIdTipoTratamientoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse obtenerPorIdTipoTratamiento(SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/obtenerPorIdTipoTratamientoR" +
            "equest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/obtenerPorIdTipoTratamientoR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse> obtenerPorIdTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/insertarTipoTratamientoReque" +
            "st", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/insertarTipoTratamientoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse insertarTipoTratamiento(SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/insertarTipoTratamientoReque" +
            "st", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/insertarTipoTratamientoRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse> insertarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/eliminarTipoTratamientoReque" +
            "st", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/eliminarTipoTratamientoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse eliminarTipoTratamiento(SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/eliminarTipoTratamientoReque" +
            "st", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/eliminarTipoTratamientoRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse> eliminarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/modificarTipoTratamientoRequ" +
            "est", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/modificarTipoTratamientoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse modificarTipoTratamiento(SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/modificarTipoTratamientoRequ" +
            "est", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/modificarTipoTratamientoResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse> modificarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/listarTodosTipoTratamientoRe" +
            "quest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/listarTodosTipoTratamientoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse listarTodosTipoTratamiento(SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/TipoTratamiento/listarTodosTipoTratamientoRe" +
            "quest", ReplyAction="http://services.softgest.pucp.edu.pe/TipoTratamiento/listarTodosTipoTratamientoRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse> listarTodosTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoTratamientoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoTratamientoField;
        
        private bool idTipoTratamientoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoTratamiento {
            get {
                return this.idTipoTratamientoField;
            }
            set {
                this.idTipoTratamientoField = value;
                this.RaisePropertyChanged("idTipoTratamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoTratamientoSpecified {
            get {
                return this.idTipoTratamientoFieldSpecified;
            }
            set {
                this.idTipoTratamientoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoTratamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoTratamiento;
        
        public obtenerPorIdTipoTratamientoRequest() {
        }
        
        public obtenerPorIdTipoTratamientoRequest(int idTipoTratamiento) {
            this.idTipoTratamiento = idTipoTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTipoTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdTipoTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO @return;
        
        public obtenerPorIdTipoTratamientoResponse() {
        }
        
        public obtenerPorIdTipoTratamientoResponse(SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public insertarTipoTratamientoRequest() {
        }
        
        public insertarTipoTratamientoRequest(string nombre, string descripcion) {
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoTratamientoResponse() {
        }
        
        public insertarTipoTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoTratamiento;
        
        public eliminarTipoTratamientoRequest() {
        }
        
        public eliminarTipoTratamientoRequest(int idTipoTratamiento) {
            this.idTipoTratamiento = idTipoTratamiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTipoTratamientoResponse() {
        }
        
        public eliminarTipoTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoTratamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoTratamiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public modificarTipoTratamientoRequest() {
        }
        
        public modificarTipoTratamientoRequest(int idTipoTratamiento, string nombre, string descripcion) {
            this.idTipoTratamiento = idTipoTratamiento;
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTipoTratamientoResponse() {
        }
        
        public modificarTipoTratamientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoTratamiento", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoTratamientoRequest {
        
        public listarTodosTipoTratamientoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipoTratamientoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTipoTratamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO[] @return;
        
        public listarTodosTipoTratamientoResponse() {
        }
        
        public listarTodosTipoTratamientoResponse(SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoTratamientoChannel : SoftGestWA.TipoTratamientoWS.TipoTratamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoTratamientoClient : System.ServiceModel.ClientBase<SoftGestWA.TipoTratamientoWS.TipoTratamiento>, SoftGestWA.TipoTratamientoWS.TipoTratamiento {
        
        public TipoTratamientoClient() {
        }
        
        public TipoTratamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoTratamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoTratamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoTratamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse SoftGestWA.TipoTratamientoWS.TipoTratamiento.obtenerPorIdTipoTratamiento(SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest request) {
            return base.Channel.obtenerPorIdTipoTratamiento(request);
        }
        
        public SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO obtenerPorIdTipoTratamiento(int idTipoTratamiento) {
            SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse retVal = ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).obtenerPorIdTipoTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse> SoftGestWA.TipoTratamientoWS.TipoTratamiento.obtenerPorIdTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest request) {
            return base.Channel.obtenerPorIdTipoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoResponse> obtenerPorIdTipoTratamientoAsync(int idTipoTratamiento) {
            SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.obtenerPorIdTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            return ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).obtenerPorIdTipoTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse SoftGestWA.TipoTratamientoWS.TipoTratamiento.insertarTipoTratamiento(SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest request) {
            return base.Channel.insertarTipoTratamiento(request);
        }
        
        public int insertarTipoTratamiento(string nombre, string descripcion) {
            SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse retVal = ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).insertarTipoTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse> SoftGestWA.TipoTratamientoWS.TipoTratamiento.insertarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest request) {
            return base.Channel.insertarTipoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoResponse> insertarTipoTratamientoAsync(string nombre, string descripcion) {
            SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.insertarTipoTratamientoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).insertarTipoTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse SoftGestWA.TipoTratamientoWS.TipoTratamiento.eliminarTipoTratamiento(SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest request) {
            return base.Channel.eliminarTipoTratamiento(request);
        }
        
        public int eliminarTipoTratamiento(int idTipoTratamiento) {
            SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse retVal = ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).eliminarTipoTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse> SoftGestWA.TipoTratamientoWS.TipoTratamiento.eliminarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest request) {
            return base.Channel.eliminarTipoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoResponse> eliminarTipoTratamientoAsync(int idTipoTratamiento) {
            SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.eliminarTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            return ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).eliminarTipoTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse SoftGestWA.TipoTratamientoWS.TipoTratamiento.modificarTipoTratamiento(SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest request) {
            return base.Channel.modificarTipoTratamiento(request);
        }
        
        public int modificarTipoTratamiento(int idTipoTratamiento, string nombre, string descripcion) {
            SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse retVal = ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).modificarTipoTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse> SoftGestWA.TipoTratamientoWS.TipoTratamiento.modificarTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest request) {
            return base.Channel.modificarTipoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoResponse> modificarTipoTratamientoAsync(int idTipoTratamiento, string nombre, string descripcion) {
            SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.modificarTipoTratamientoRequest();
            inValue.idTipoTratamiento = idTipoTratamiento;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).modificarTipoTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse SoftGestWA.TipoTratamientoWS.TipoTratamiento.listarTodosTipoTratamiento(SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest request) {
            return base.Channel.listarTodosTipoTratamiento(request);
        }
        
        public SoftGestWA.TipoTratamientoWS.tipoTratamientoDTO[] listarTodosTipoTratamiento() {
            SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest();
            SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse retVal = ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).listarTodosTipoTratamiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse> SoftGestWA.TipoTratamientoWS.TipoTratamiento.listarTodosTipoTratamientoAsync(SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest request) {
            return base.Channel.listarTodosTipoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoResponse> listarTodosTipoTratamientoAsync() {
            SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest inValue = new SoftGestWA.TipoTratamientoWS.listarTodosTipoTratamientoRequest();
            return ((SoftGestWA.TipoTratamientoWS.TipoTratamiento)(this)).listarTodosTipoTratamientoAsync(inValue);
        }
    }
}
