//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="UsuarioWS.Usuario")]
    public interface Usuario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/obtenerPorIdUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/obtenerPorIdUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse obtenerPorIdUsuario(SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/obtenerPorIdUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/obtenerPorIdUsuarioResponse")]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse> obtenerPorIdUsuarioAsync(SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.UsuarioWS.insertarUsuarioResponse insertarUsuario(SoftGestWA.UsuarioWS.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.insertarUsuarioResponse> insertarUsuarioAsync(SoftGestWA.UsuarioWS.insertarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.UsuarioWS.modificarUsuarioResponse modificarUsuario(SoftGestWA.UsuarioWS.modificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.modificarUsuarioResponse> modificarUsuarioAsync(SoftGestWA.UsuarioWS.modificarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/eliminarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/eliminarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.UsuarioWS.eliminarUsuarioResponse eliminarUsuario(SoftGestWA.UsuarioWS.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/eliminarUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/eliminarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.eliminarUsuarioResponse> eliminarUsuarioAsync(SoftGestWA.UsuarioWS.eliminarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/listarTodosUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/listarTodosUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.UsuarioWS.listarTodosUsuarioResponse listarTodosUsuario(SoftGestWA.UsuarioWS.listarTodosUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Usuario/listarTodosUsuarioRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Usuario/listarTodosUsuarioResponse")]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.listarTodosUsuarioResponse> listarTodosUsuarioAsync(SoftGestWA.UsuarioWS.listarTodosUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombresField;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        Masculino,
        
        /// <remarks/>
        Femenino,
        
        /// <remarks/>
        OTRO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdUsuario", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public obtenerPorIdUsuarioRequest() {
        }
        
        public obtenerPorIdUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdUsuarioResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.usuarioDTO @return;
        
        public obtenerPorIdUsuarioResponse() {
        }
        
        public obtenerPorIdUsuarioResponse(SoftGestWA.UsuarioWS.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.sexo sexo;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum turno {
        
        /// <remarks/>
        Mañana,
        
        /// <remarks/>
        Tarde,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum disponibilidad {
        
        /// <remarks/>
        Disponible,
        
        /// <remarks/>
        NoDisponible,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuario", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.sexo sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.turno turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.disponibilidad estado;
        
        public modificarUsuarioRequest() {
        }
        
        public modificarUsuarioRequest(int idUsuario, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo, SoftGestWA.UsuarioWS.turno turno, SoftGestWA.UsuarioWS.disponibilidad estado) {
            this.idUsuario = idUsuario;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
            this.turno = turno;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuarioResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarUsuarioResponse() {
        }
        
        public modificarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuario", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuarioResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuario", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuarioRequest {
        
        public listarTodosUsuarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuarioResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.UsuarioWS.usuarioDTO[] @return;
        
        public listarTodosUsuarioResponse() {
        }
        
        public listarTodosUsuarioResponse(SoftGestWA.UsuarioWS.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioChannel : SoftGestWA.UsuarioWS.Usuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<SoftGestWA.UsuarioWS.Usuario>, SoftGestWA.UsuarioWS.Usuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse SoftGestWA.UsuarioWS.Usuario.obtenerPorIdUsuario(SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest request) {
            return base.Channel.obtenerPorIdUsuario(request);
        }
        
        public SoftGestWA.UsuarioWS.usuarioDTO obtenerPorIdUsuario(int idUsuario) {
            SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest inValue = new SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest();
            inValue.idUsuario = idUsuario;
            SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse retVal = ((SoftGestWA.UsuarioWS.Usuario)(this)).obtenerPorIdUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse> SoftGestWA.UsuarioWS.Usuario.obtenerPorIdUsuarioAsync(SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest request) {
            return base.Channel.obtenerPorIdUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.obtenerPorIdUsuarioResponse> obtenerPorIdUsuarioAsync(int idUsuario) {
            SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest inValue = new SoftGestWA.UsuarioWS.obtenerPorIdUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((SoftGestWA.UsuarioWS.Usuario)(this)).obtenerPorIdUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.UsuarioWS.insertarUsuarioResponse SoftGestWA.UsuarioWS.Usuario.insertarUsuario(SoftGestWA.UsuarioWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public int insertarUsuario(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo) {
            SoftGestWA.UsuarioWS.insertarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.insertarUsuarioRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            SoftGestWA.UsuarioWS.insertarUsuarioResponse retVal = ((SoftGestWA.UsuarioWS.Usuario)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.insertarUsuarioResponse> SoftGestWA.UsuarioWS.Usuario.insertarUsuarioAsync(SoftGestWA.UsuarioWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.insertarUsuarioResponse> insertarUsuarioAsync(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo) {
            SoftGestWA.UsuarioWS.insertarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.insertarUsuarioRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            return ((SoftGestWA.UsuarioWS.Usuario)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.UsuarioWS.modificarUsuarioResponse SoftGestWA.UsuarioWS.Usuario.modificarUsuario(SoftGestWA.UsuarioWS.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuario(request);
        }
        
        public int modificarUsuario(int idUsuario, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo, SoftGestWA.UsuarioWS.turno turno, SoftGestWA.UsuarioWS.disponibilidad estado) {
            SoftGestWA.UsuarioWS.modificarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.modificarUsuarioRequest();
            inValue.idUsuario = idUsuario;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.turno = turno;
            inValue.estado = estado;
            SoftGestWA.UsuarioWS.modificarUsuarioResponse retVal = ((SoftGestWA.UsuarioWS.Usuario)(this)).modificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.modificarUsuarioResponse> SoftGestWA.UsuarioWS.Usuario.modificarUsuarioAsync(SoftGestWA.UsuarioWS.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.modificarUsuarioResponse> modificarUsuarioAsync(int idUsuario, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.UsuarioWS.sexo sexo, SoftGestWA.UsuarioWS.turno turno, SoftGestWA.UsuarioWS.disponibilidad estado) {
            SoftGestWA.UsuarioWS.modificarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.modificarUsuarioRequest();
            inValue.idUsuario = idUsuario;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.turno = turno;
            inValue.estado = estado;
            return ((SoftGestWA.UsuarioWS.Usuario)(this)).modificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.UsuarioWS.eliminarUsuarioResponse SoftGestWA.UsuarioWS.Usuario.eliminarUsuario(SoftGestWA.UsuarioWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public int eliminarUsuario(int idUsuario) {
            SoftGestWA.UsuarioWS.eliminarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.eliminarUsuarioRequest();
            inValue.idUsuario = idUsuario;
            SoftGestWA.UsuarioWS.eliminarUsuarioResponse retVal = ((SoftGestWA.UsuarioWS.Usuario)(this)).eliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.eliminarUsuarioResponse> SoftGestWA.UsuarioWS.Usuario.eliminarUsuarioAsync(SoftGestWA.UsuarioWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.eliminarUsuarioResponse> eliminarUsuarioAsync(int idUsuario) {
            SoftGestWA.UsuarioWS.eliminarUsuarioRequest inValue = new SoftGestWA.UsuarioWS.eliminarUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((SoftGestWA.UsuarioWS.Usuario)(this)).eliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.UsuarioWS.listarTodosUsuarioResponse SoftGestWA.UsuarioWS.Usuario.listarTodosUsuario(SoftGestWA.UsuarioWS.listarTodosUsuarioRequest request) {
            return base.Channel.listarTodosUsuario(request);
        }
        
        public SoftGestWA.UsuarioWS.usuarioDTO[] listarTodosUsuario() {
            SoftGestWA.UsuarioWS.listarTodosUsuarioRequest inValue = new SoftGestWA.UsuarioWS.listarTodosUsuarioRequest();
            SoftGestWA.UsuarioWS.listarTodosUsuarioResponse retVal = ((SoftGestWA.UsuarioWS.Usuario)(this)).listarTodosUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.listarTodosUsuarioResponse> SoftGestWA.UsuarioWS.Usuario.listarTodosUsuarioAsync(SoftGestWA.UsuarioWS.listarTodosUsuarioRequest request) {
            return base.Channel.listarTodosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.UsuarioWS.listarTodosUsuarioResponse> listarTodosUsuarioAsync() {
            SoftGestWA.UsuarioWS.listarTodosUsuarioRequest inValue = new SoftGestWA.UsuarioWS.listarTodosUsuarioRequest();
            return ((SoftGestWA.UsuarioWS.Usuario)(this)).listarTodosUsuarioAsync(inValue);
        }
    }
}
