//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.OdontologoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="OdontologoWS.Odontologo")]
    public interface Odontologo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/eliminarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/eliminarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.OdontologoWS.eliminarOdontologoResponse eliminarOdontologo(SoftGestWA.OdontologoWS.eliminarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/eliminarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/eliminarOdontologoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.eliminarOdontologoResponse> eliminarOdontologoAsync(SoftGestWA.OdontologoWS.eliminarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/insertarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/insertarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.OdontologoWS.insertarOdontologoResponse insertarOdontologo(SoftGestWA.OdontologoWS.insertarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/insertarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/insertarOdontologoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.insertarOdontologoResponse> insertarOdontologoAsync(SoftGestWA.OdontologoWS.insertarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/modificarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/modificarOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.OdontologoWS.modificarOdontologoResponse modificarOdontologo(SoftGestWA.OdontologoWS.modificarOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/modificarOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/modificarOdontologoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.modificarOdontologoResponse> modificarOdontologoAsync(SoftGestWA.OdontologoWS.modificarOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/listarTodosOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/listarTodosOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.OdontologoWS.listarTodosOdontologoResponse listarTodosOdontologo(SoftGestWA.OdontologoWS.listarTodosOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/listarTodosOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/listarTodosOdontologoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.listarTodosOdontologoResponse> listarTodosOdontologoAsync(SoftGestWA.OdontologoWS.listarTodosOdontologoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/obtenerPorIdOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/obtenerPorIdOdontologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse obtenerPorIdOdontologo(SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Odontologo/obtenerPorIdOdontologoRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Odontologo/obtenerPorIdOdontologoResponse")]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse> obtenerPorIdOdontologoAsync(SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOdontologo", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOdontologo;
        
        public eliminarOdontologoRequest() {
        }
        
        public eliminarOdontologoRequest(int idOdontologo) {
            this.idOdontologo = idOdontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOdontologoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOdontologoResponse() {
        }
        
        public eliminarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class turnoPersonalDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private disponibilidad estadoField;
        
        private bool estadoFieldSpecified;
        
        private int idTurnoPersonalField;
        
        private bool idTurnoPersonalFieldSpecified;
        
        private turno turnoField;
        
        private bool turnoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public disponibilidad estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTurnoPersonal {
            get {
                return this.idTurnoPersonalField;
            }
            set {
                this.idTurnoPersonalField = value;
                this.RaisePropertyChanged("idTurnoPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTurnoPersonalSpecified {
            get {
                return this.idTurnoPersonalFieldSpecified;
            }
            set {
                this.idTurnoPersonalFieldSpecified = value;
                this.RaisePropertyChanged("idTurnoPersonalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public turno turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum disponibilidad {
        
        /// <remarks/>
        Disponible,
        
        /// <remarks/>
        NoDisponible,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum turno {
        
        /// <remarks/>
        Mañana,
        
        /// <remarks/>
        Tarde,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(odontologoDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombresField;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        Masculino,
        
        /// <remarks/>
        Femenino,
        
        /// <remarks/>
        OTRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class odontologoDTO : usuarioDTO {
        
        private especialidad especialidadField;
        
        private bool especialidadFieldSpecified;
        
        private disponibilidad estadoField;
        
        private bool estadoFieldSpecified;
        
        private turno turnoField;
        
        private bool turnoFieldSpecified;
        
        private turnoPersonalDTO turnoPersonalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool especialidadSpecified {
            get {
                return this.especialidadFieldSpecified;
            }
            set {
                this.especialidadFieldSpecified = value;
                this.RaisePropertyChanged("especialidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public disponibilidad estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public turno turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public turnoPersonalDTO turnoPersonal {
            get {
                return this.turnoPersonalField;
            }
            set {
                this.turnoPersonalField = value;
                this.RaisePropertyChanged("turnoPersonal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum especialidad {
        
        /// <remarks/>
        Ortodoncia,
        
        /// <remarks/>
        Endodoncia,
        
        /// <remarks/>
        Peridoncia,
        
        /// <remarks/>
        Implantologia,
        
        /// <remarks/>
        Radiologia,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOdontologo", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.date fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.sexo sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.especialidad especialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.turno turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.disponibilidad estado;
        
        public insertarOdontologoRequest() {
        }
        
        public insertarOdontologoRequest(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
            this.especialidad = especialidad;
            this.turno = turno;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOdontologoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOdontologoResponse() {
        }
        
        public insertarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOdontologo", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOdontologo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.date fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.sexo sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.especialidad especialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.turno turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.disponibilidad estado;
        
        public modificarOdontologoRequest() {
        }
        
        public modificarOdontologoRequest(int idOdontologo, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            this.idOdontologo = idOdontologo;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
            this.especialidad = especialidad;
            this.turno = turno;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOdontologoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarOdontologoResponse() {
        }
        
        public modificarOdontologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosOdontologo", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosOdontologoRequest {
        
        public listarTodosOdontologoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosOdontologoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.odontologoDTO[] @return;
        
        public listarTodosOdontologoResponse() {
        }
        
        public listarTodosOdontologoResponse(SoftGestWA.OdontologoWS.odontologoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdOdontologo", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdOdontologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOdontologo;
        
        public obtenerPorIdOdontologoRequest() {
        }
        
        public obtenerPorIdOdontologoRequest(int idOdontologo) {
            this.idOdontologo = idOdontologo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdOdontologoResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdOdontologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.OdontologoWS.odontologoDTO @return;
        
        public obtenerPorIdOdontologoResponse() {
        }
        
        public obtenerPorIdOdontologoResponse(SoftGestWA.OdontologoWS.odontologoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdontologoChannel : SoftGestWA.OdontologoWS.Odontologo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdontologoClient : System.ServiceModel.ClientBase<SoftGestWA.OdontologoWS.Odontologo>, SoftGestWA.OdontologoWS.Odontologo {
        
        public OdontologoClient() {
        }
        
        public OdontologoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdontologoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdontologoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdontologoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.OdontologoWS.eliminarOdontologoResponse SoftGestWA.OdontologoWS.Odontologo.eliminarOdontologo(SoftGestWA.OdontologoWS.eliminarOdontologoRequest request) {
            return base.Channel.eliminarOdontologo(request);
        }
        
        public int eliminarOdontologo(int idOdontologo) {
            SoftGestWA.OdontologoWS.eliminarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.eliminarOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            SoftGestWA.OdontologoWS.eliminarOdontologoResponse retVal = ((SoftGestWA.OdontologoWS.Odontologo)(this)).eliminarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.eliminarOdontologoResponse> SoftGestWA.OdontologoWS.Odontologo.eliminarOdontologoAsync(SoftGestWA.OdontologoWS.eliminarOdontologoRequest request) {
            return base.Channel.eliminarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.eliminarOdontologoResponse> eliminarOdontologoAsync(int idOdontologo) {
            SoftGestWA.OdontologoWS.eliminarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.eliminarOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            return ((SoftGestWA.OdontologoWS.Odontologo)(this)).eliminarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.OdontologoWS.insertarOdontologoResponse SoftGestWA.OdontologoWS.Odontologo.insertarOdontologo(SoftGestWA.OdontologoWS.insertarOdontologoRequest request) {
            return base.Channel.insertarOdontologo(request);
        }
        
        public int insertarOdontologo(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            SoftGestWA.OdontologoWS.insertarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.insertarOdontologoRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.especialidad = especialidad;
            inValue.turno = turno;
            inValue.estado = estado;
            SoftGestWA.OdontologoWS.insertarOdontologoResponse retVal = ((SoftGestWA.OdontologoWS.Odontologo)(this)).insertarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.insertarOdontologoResponse> SoftGestWA.OdontologoWS.Odontologo.insertarOdontologoAsync(SoftGestWA.OdontologoWS.insertarOdontologoRequest request) {
            return base.Channel.insertarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.insertarOdontologoResponse> insertarOdontologoAsync(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            SoftGestWA.OdontologoWS.insertarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.insertarOdontologoRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.especialidad = especialidad;
            inValue.turno = turno;
            inValue.estado = estado;
            return ((SoftGestWA.OdontologoWS.Odontologo)(this)).insertarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.OdontologoWS.modificarOdontologoResponse SoftGestWA.OdontologoWS.Odontologo.modificarOdontologo(SoftGestWA.OdontologoWS.modificarOdontologoRequest request) {
            return base.Channel.modificarOdontologo(request);
        }
        
        public int modificarOdontologo(int idOdontologo, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            SoftGestWA.OdontologoWS.modificarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.modificarOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.especialidad = especialidad;
            inValue.turno = turno;
            inValue.estado = estado;
            SoftGestWA.OdontologoWS.modificarOdontologoResponse retVal = ((SoftGestWA.OdontologoWS.Odontologo)(this)).modificarOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.modificarOdontologoResponse> SoftGestWA.OdontologoWS.Odontologo.modificarOdontologoAsync(SoftGestWA.OdontologoWS.modificarOdontologoRequest request) {
            return base.Channel.modificarOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.modificarOdontologoResponse> modificarOdontologoAsync(int idOdontologo, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, SoftGestWA.OdontologoWS.date fechaNacimiento, SoftGestWA.OdontologoWS.sexo sexo, SoftGestWA.OdontologoWS.especialidad especialidad, SoftGestWA.OdontologoWS.turno turno, SoftGestWA.OdontologoWS.disponibilidad estado) {
            SoftGestWA.OdontologoWS.modificarOdontologoRequest inValue = new SoftGestWA.OdontologoWS.modificarOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            inValue.especialidad = especialidad;
            inValue.turno = turno;
            inValue.estado = estado;
            return ((SoftGestWA.OdontologoWS.Odontologo)(this)).modificarOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.OdontologoWS.listarTodosOdontologoResponse SoftGestWA.OdontologoWS.Odontologo.listarTodosOdontologo(SoftGestWA.OdontologoWS.listarTodosOdontologoRequest request) {
            return base.Channel.listarTodosOdontologo(request);
        }
        
        public SoftGestWA.OdontologoWS.odontologoDTO[] listarTodosOdontologo() {
            SoftGestWA.OdontologoWS.listarTodosOdontologoRequest inValue = new SoftGestWA.OdontologoWS.listarTodosOdontologoRequest();
            SoftGestWA.OdontologoWS.listarTodosOdontologoResponse retVal = ((SoftGestWA.OdontologoWS.Odontologo)(this)).listarTodosOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.listarTodosOdontologoResponse> SoftGestWA.OdontologoWS.Odontologo.listarTodosOdontologoAsync(SoftGestWA.OdontologoWS.listarTodosOdontologoRequest request) {
            return base.Channel.listarTodosOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.listarTodosOdontologoResponse> listarTodosOdontologoAsync() {
            SoftGestWA.OdontologoWS.listarTodosOdontologoRequest inValue = new SoftGestWA.OdontologoWS.listarTodosOdontologoRequest();
            return ((SoftGestWA.OdontologoWS.Odontologo)(this)).listarTodosOdontologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse SoftGestWA.OdontologoWS.Odontologo.obtenerPorIdOdontologo(SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest request) {
            return base.Channel.obtenerPorIdOdontologo(request);
        }
        
        public SoftGestWA.OdontologoWS.odontologoDTO obtenerPorIdOdontologo(int idOdontologo) {
            SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest inValue = new SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse retVal = ((SoftGestWA.OdontologoWS.Odontologo)(this)).obtenerPorIdOdontologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse> SoftGestWA.OdontologoWS.Odontologo.obtenerPorIdOdontologoAsync(SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest request) {
            return base.Channel.obtenerPorIdOdontologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.OdontologoWS.obtenerPorIdOdontologoResponse> obtenerPorIdOdontologoAsync(int idOdontologo) {
            SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest inValue = new SoftGestWA.OdontologoWS.obtenerPorIdOdontologoRequest();
            inValue.idOdontologo = idOdontologo;
            return ((SoftGestWA.OdontologoWS.Odontologo)(this)).obtenerPorIdOdontologoAsync(inValue);
        }
    }
}
