//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.JefeAlmacenWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="JefeAlmacenWS.JefeAlmacen")]
    public interface JefeAlmacen {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/eliminarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/eliminarJefeAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse eliminarJefeAlmacen(SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/eliminarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/eliminarJefeAlmacenResponse")]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse> eliminarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/modificarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/modificarJefeAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse modificarJefeAlmacen(SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/modificarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/modificarJefeAlmacenResponse")]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse> modificarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/insertarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/insertarJefeAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse insertarJefeAlmacen(SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/insertarJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/insertarJefeAlmacenResponse")]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse> insertarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/obtenerPorIdJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/obtenerPorIdJefeAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse obtenerPorIdJefeAlmacen(SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/obtenerPorIdJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/obtenerPorIdJefeAlmacenResponse")]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse> obtenerPorIdJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/listarTodosJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/listarTodosJefeAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse listarTodosJefeAlmacen(SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/JefeAlmacen/listarTodosJefeAlmacenRequest", ReplyAction="http://services.softgest.pucp.edu.pe/JefeAlmacen/listarTodosJefeAlmacenResponse")]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse> listarTodosJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJefeAlmacen", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarJefeAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefeAlmacen;
        
        public eliminarJefeAlmacenRequest() {
        }
        
        public eliminarJefeAlmacenRequest(int idJefeAlmacen) {
            this.idJefeAlmacen = idJefeAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJefeAlmacenResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarJefeAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarJefeAlmacenResponse() {
        }
        
        public eliminarJefeAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        Masculino,
        
        /// <remarks/>
        Femenino,
        
        /// <remarks/>
        OTRO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJefeAlmacen", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarJefeAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefeAlmacen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.JefeAlmacenWS.sexo sexo;
        
        public modificarJefeAlmacenRequest() {
        }
        
        public modificarJefeAlmacenRequest(int idJefeAlmacen, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            this.idJefeAlmacen = idJefeAlmacen;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJefeAlmacenResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarJefeAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarJefeAlmacenResponse() {
        }
        
        public modificarJefeAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJefeAlmacen", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarJefeAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.JefeAlmacenWS.sexo sexo;
        
        public insertarJefeAlmacenRequest() {
        }
        
        public insertarJefeAlmacenRequest(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.dni = dni;
            this.telefono = telefono;
            this.correo = correo;
            this.direccion = direccion;
            this.fechaNacimiento = fechaNacimiento;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJefeAlmacenResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarJefeAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarJefeAlmacenResponse() {
        }
        
        public insertarJefeAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class jefeAlmacenDTO : usuarioDTO {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jefeAlmacenDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombresField;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdJefeAlmacen", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdJefeAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefeAlmacen;
        
        public obtenerPorIdJefeAlmacenRequest() {
        }
        
        public obtenerPorIdJefeAlmacenRequest(int idJefeAlmacen) {
            this.idJefeAlmacen = idJefeAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdJefeAlmacenResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdJefeAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO @return;
        
        public obtenerPorIdJefeAlmacenResponse() {
        }
        
        public obtenerPorIdJefeAlmacenResponse(SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosJefeAlmacen", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosJefeAlmacenRequest {
        
        public listarTodosJefeAlmacenRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosJefeAlmacenResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosJefeAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO[] @return;
        
        public listarTodosJefeAlmacenResponse() {
        }
        
        public listarTodosJefeAlmacenResponse(SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JefeAlmacenChannel : SoftGestWA.JefeAlmacenWS.JefeAlmacen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JefeAlmacenClient : System.ServiceModel.ClientBase<SoftGestWA.JefeAlmacenWS.JefeAlmacen>, SoftGestWA.JefeAlmacenWS.JefeAlmacen {
        
        public JefeAlmacenClient() {
        }
        
        public JefeAlmacenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JefeAlmacenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JefeAlmacenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JefeAlmacenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse SoftGestWA.JefeAlmacenWS.JefeAlmacen.eliminarJefeAlmacen(SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest request) {
            return base.Channel.eliminarJefeAlmacen(request);
        }
        
        public int eliminarJefeAlmacen(int idJefeAlmacen) {
            SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse retVal = ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).eliminarJefeAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse> SoftGestWA.JefeAlmacenWS.JefeAlmacen.eliminarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest request) {
            return base.Channel.eliminarJefeAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenResponse> eliminarJefeAlmacenAsync(int idJefeAlmacen) {
            SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.eliminarJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            return ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).eliminarJefeAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse SoftGestWA.JefeAlmacenWS.JefeAlmacen.modificarJefeAlmacen(SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest request) {
            return base.Channel.modificarJefeAlmacen(request);
        }
        
        public int modificarJefeAlmacen(int idJefeAlmacen, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse retVal = ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).modificarJefeAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse> SoftGestWA.JefeAlmacenWS.JefeAlmacen.modificarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest request) {
            return base.Channel.modificarJefeAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenResponse> modificarJefeAlmacenAsync(int idJefeAlmacen, string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.modificarJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            return ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).modificarJefeAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse SoftGestWA.JefeAlmacenWS.JefeAlmacen.insertarJefeAlmacen(SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest request) {
            return base.Channel.insertarJefeAlmacen(request);
        }
        
        public int insertarJefeAlmacen(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse retVal = ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).insertarJefeAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse> SoftGestWA.JefeAlmacenWS.JefeAlmacen.insertarJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest request) {
            return base.Channel.insertarJefeAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenResponse> insertarJefeAlmacenAsync(string nombres, string apellidos, string dni, string telefono, string correo, string direccion, System.DateTime fechaNacimiento, SoftGestWA.JefeAlmacenWS.sexo sexo) {
            SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.insertarJefeAlmacenRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.dni = dni;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.direccion = direccion;
            inValue.fechaNacimiento = fechaNacimiento;
            inValue.sexo = sexo;
            return ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).insertarJefeAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse SoftGestWA.JefeAlmacenWS.JefeAlmacen.obtenerPorIdJefeAlmacen(SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest request) {
            return base.Channel.obtenerPorIdJefeAlmacen(request);
        }
        
        public SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO obtenerPorIdJefeAlmacen(int idJefeAlmacen) {
            SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse retVal = ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).obtenerPorIdJefeAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse> SoftGestWA.JefeAlmacenWS.JefeAlmacen.obtenerPorIdJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest request) {
            return base.Channel.obtenerPorIdJefeAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenResponse> obtenerPorIdJefeAlmacenAsync(int idJefeAlmacen) {
            SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.obtenerPorIdJefeAlmacenRequest();
            inValue.idJefeAlmacen = idJefeAlmacen;
            return ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).obtenerPorIdJefeAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse SoftGestWA.JefeAlmacenWS.JefeAlmacen.listarTodosJefeAlmacen(SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest request) {
            return base.Channel.listarTodosJefeAlmacen(request);
        }
        
        public SoftGestWA.JefeAlmacenWS.jefeAlmacenDTO[] listarTodosJefeAlmacen() {
            SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest();
            SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse retVal = ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).listarTodosJefeAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse> SoftGestWA.JefeAlmacenWS.JefeAlmacen.listarTodosJefeAlmacenAsync(SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest request) {
            return base.Channel.listarTodosJefeAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenResponse> listarTodosJefeAlmacenAsync() {
            SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest inValue = new SoftGestWA.JefeAlmacenWS.listarTodosJefeAlmacenRequest();
            return ((SoftGestWA.JefeAlmacenWS.JefeAlmacen)(this)).listarTodosJefeAlmacenAsync(inValue);
        }
    }
}
