//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.MaquinaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="MaquinaWS.Maquina")]
    public interface Maquina {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/listarTodosMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/listarTodosMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaquinaWS.listarTodosMaquinaResponse listarTodosMaquina(SoftGestWA.MaquinaWS.listarTodosMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/listarTodosMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/listarTodosMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.listarTodosMaquinaResponse> listarTodosMaquinaAsync(SoftGestWA.MaquinaWS.listarTodosMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/eliminarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/eliminarMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaquinaWS.eliminarMaquinaResponse eliminarMaquina(SoftGestWA.MaquinaWS.eliminarMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/eliminarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/eliminarMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.eliminarMaquinaResponse> eliminarMaquinaAsync(SoftGestWA.MaquinaWS.eliminarMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/modificarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/modificarMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaquinaWS.modificarMaquinaResponse modificarMaquina(SoftGestWA.MaquinaWS.modificarMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/modificarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/modificarMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.modificarMaquinaResponse> modificarMaquinaAsync(SoftGestWA.MaquinaWS.modificarMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/insertarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/insertarMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaquinaWS.insertarMaquinaResponse insertarMaquina(SoftGestWA.MaquinaWS.insertarMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/insertarMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/insertarMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.insertarMaquinaResponse> insertarMaquinaAsync(SoftGestWA.MaquinaWS.insertarMaquinaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/obtenerPorIdMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/obtenerPorIdMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse obtenerPorIdMaquina(SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Maquina/obtenerPorIdMaquinaRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Maquina/obtenerPorIdMaquinaResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse> obtenerPorIdMaquinaAsync(SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class maquinaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoMaquina estadoField;
        
        private bool estadoFieldSpecified;
        
        private int idMaquinaField;
        
        private bool idMaquinaFieldSpecified;
        
        private string marcaField;
        
        private string modeloField;
        
        private string nombreField;
        
        private tipoMaquinaDTO tipoMaquinaDTOField;
        
        private date ultimaRevisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoMaquina estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMaquina {
            get {
                return this.idMaquinaField;
            }
            set {
                this.idMaquinaField = value;
                this.RaisePropertyChanged("idMaquina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMaquinaSpecified {
            get {
                return this.idMaquinaFieldSpecified;
            }
            set {
                this.idMaquinaFieldSpecified = value;
                this.RaisePropertyChanged("idMaquinaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoMaquinaDTO tipoMaquinaDTO {
            get {
                return this.tipoMaquinaDTOField;
            }
            set {
                this.tipoMaquinaDTOField = value;
                this.RaisePropertyChanged("tipoMaquinaDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public date ultimaRevision {
            get {
                return this.ultimaRevisionField;
            }
            set {
                this.ultimaRevisionField = value;
                this.RaisePropertyChanged("ultimaRevision");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public enum estadoMaquina {
        
        /// <remarks/>
        Operativa,
        
        /// <remarks/>
        Malograda,
        
        /// <remarks/>
        En_Mantenimiento,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoMaquinaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoMaquinasField;
        
        private bool idTipoMaquinasFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoMaquinas {
            get {
                return this.idTipoMaquinasField;
            }
            set {
                this.idTipoMaquinasField = value;
                this.RaisePropertyChanged("idTipoMaquinas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMaquinasSpecified {
            get {
                return this.idTipoMaquinasFieldSpecified;
            }
            set {
                this.idTipoMaquinasFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMaquinasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMaquinaRequest {
        
        public listarTodosMaquinaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.maquinaDTO[] @return;
        
        public listarTodosMaquinaResponse() {
        }
        
        public listarTodosMaquinaResponse(SoftGestWA.MaquinaWS.maquinaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaquina;
        
        public eliminarMaquinaRequest() {
        }
        
        public eliminarMaquinaRequest(int idMaquina) {
            this.idMaquina = idMaquina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMaquinaResponse() {
        }
        
        public eliminarMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.date ultimaRevision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        public modificarMaquinaRequest() {
        }
        
        public modificarMaquinaRequest(int idMaquina, string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            this.idMaquina = idMaquina;
            this.nombre = nombre;
            this.ultimaRevision = ultimaRevision;
            this.estadoMaquina = estadoMaquina;
            this.idTipoMaquina = idTipoMaquina;
            this.marca = marca;
            this.modelo = modelo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMaquinaResponse() {
        }
        
        public modificarMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.date ultimaRevision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        public insertarMaquinaRequest() {
        }
        
        public insertarMaquinaRequest(string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            this.nombre = nombre;
            this.ultimaRevision = ultimaRevision;
            this.estadoMaquina = estadoMaquina;
            this.idTipoMaquina = idTipoMaquina;
            this.marca = marca;
            this.modelo = modelo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMaquinaResponse() {
        }
        
        public insertarMaquinaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMaquina", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMaquinaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaquina;
        
        public obtenerPorIdMaquinaRequest() {
        }
        
        public obtenerPorIdMaquinaRequest(int idMaquina) {
            this.idMaquina = idMaquina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMaquinaResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMaquinaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaquinaWS.maquinaDTO @return;
        
        public obtenerPorIdMaquinaResponse() {
        }
        
        public obtenerPorIdMaquinaResponse(SoftGestWA.MaquinaWS.maquinaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaquinaChannel : SoftGestWA.MaquinaWS.Maquina, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaquinaClient : System.ServiceModel.ClientBase<SoftGestWA.MaquinaWS.Maquina>, SoftGestWA.MaquinaWS.Maquina {
        
        public MaquinaClient() {
        }
        
        public MaquinaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaquinaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaquinaWS.listarTodosMaquinaResponse SoftGestWA.MaquinaWS.Maquina.listarTodosMaquina(SoftGestWA.MaquinaWS.listarTodosMaquinaRequest request) {
            return base.Channel.listarTodosMaquina(request);
        }
        
        public SoftGestWA.MaquinaWS.maquinaDTO[] listarTodosMaquina() {
            SoftGestWA.MaquinaWS.listarTodosMaquinaRequest inValue = new SoftGestWA.MaquinaWS.listarTodosMaquinaRequest();
            SoftGestWA.MaquinaWS.listarTodosMaquinaResponse retVal = ((SoftGestWA.MaquinaWS.Maquina)(this)).listarTodosMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.listarTodosMaquinaResponse> SoftGestWA.MaquinaWS.Maquina.listarTodosMaquinaAsync(SoftGestWA.MaquinaWS.listarTodosMaquinaRequest request) {
            return base.Channel.listarTodosMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.listarTodosMaquinaResponse> listarTodosMaquinaAsync() {
            SoftGestWA.MaquinaWS.listarTodosMaquinaRequest inValue = new SoftGestWA.MaquinaWS.listarTodosMaquinaRequest();
            return ((SoftGestWA.MaquinaWS.Maquina)(this)).listarTodosMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaquinaWS.eliminarMaquinaResponse SoftGestWA.MaquinaWS.Maquina.eliminarMaquina(SoftGestWA.MaquinaWS.eliminarMaquinaRequest request) {
            return base.Channel.eliminarMaquina(request);
        }
        
        public int eliminarMaquina(int idMaquina) {
            SoftGestWA.MaquinaWS.eliminarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.eliminarMaquinaRequest();
            inValue.idMaquina = idMaquina;
            SoftGestWA.MaquinaWS.eliminarMaquinaResponse retVal = ((SoftGestWA.MaquinaWS.Maquina)(this)).eliminarMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.eliminarMaquinaResponse> SoftGestWA.MaquinaWS.Maquina.eliminarMaquinaAsync(SoftGestWA.MaquinaWS.eliminarMaquinaRequest request) {
            return base.Channel.eliminarMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.eliminarMaquinaResponse> eliminarMaquinaAsync(int idMaquina) {
            SoftGestWA.MaquinaWS.eliminarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.eliminarMaquinaRequest();
            inValue.idMaquina = idMaquina;
            return ((SoftGestWA.MaquinaWS.Maquina)(this)).eliminarMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaquinaWS.modificarMaquinaResponse SoftGestWA.MaquinaWS.Maquina.modificarMaquina(SoftGestWA.MaquinaWS.modificarMaquinaRequest request) {
            return base.Channel.modificarMaquina(request);
        }
        
        public int modificarMaquina(int idMaquina, string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            SoftGestWA.MaquinaWS.modificarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.modificarMaquinaRequest();
            inValue.idMaquina = idMaquina;
            inValue.nombre = nombre;
            inValue.ultimaRevision = ultimaRevision;
            inValue.estadoMaquina = estadoMaquina;
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.marca = marca;
            inValue.modelo = modelo;
            SoftGestWA.MaquinaWS.modificarMaquinaResponse retVal = ((SoftGestWA.MaquinaWS.Maquina)(this)).modificarMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.modificarMaquinaResponse> SoftGestWA.MaquinaWS.Maquina.modificarMaquinaAsync(SoftGestWA.MaquinaWS.modificarMaquinaRequest request) {
            return base.Channel.modificarMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.modificarMaquinaResponse> modificarMaquinaAsync(int idMaquina, string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            SoftGestWA.MaquinaWS.modificarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.modificarMaquinaRequest();
            inValue.idMaquina = idMaquina;
            inValue.nombre = nombre;
            inValue.ultimaRevision = ultimaRevision;
            inValue.estadoMaquina = estadoMaquina;
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.marca = marca;
            inValue.modelo = modelo;
            return ((SoftGestWA.MaquinaWS.Maquina)(this)).modificarMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaquinaWS.insertarMaquinaResponse SoftGestWA.MaquinaWS.Maquina.insertarMaquina(SoftGestWA.MaquinaWS.insertarMaquinaRequest request) {
            return base.Channel.insertarMaquina(request);
        }
        
        public int insertarMaquina(string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            SoftGestWA.MaquinaWS.insertarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.insertarMaquinaRequest();
            inValue.nombre = nombre;
            inValue.ultimaRevision = ultimaRevision;
            inValue.estadoMaquina = estadoMaquina;
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.marca = marca;
            inValue.modelo = modelo;
            SoftGestWA.MaquinaWS.insertarMaquinaResponse retVal = ((SoftGestWA.MaquinaWS.Maquina)(this)).insertarMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.insertarMaquinaResponse> SoftGestWA.MaquinaWS.Maquina.insertarMaquinaAsync(SoftGestWA.MaquinaWS.insertarMaquinaRequest request) {
            return base.Channel.insertarMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.insertarMaquinaResponse> insertarMaquinaAsync(string nombre, SoftGestWA.MaquinaWS.date ultimaRevision, SoftGestWA.MaquinaWS.estadoMaquina estadoMaquina, int idTipoMaquina, string marca, string modelo) {
            SoftGestWA.MaquinaWS.insertarMaquinaRequest inValue = new SoftGestWA.MaquinaWS.insertarMaquinaRequest();
            inValue.nombre = nombre;
            inValue.ultimaRevision = ultimaRevision;
            inValue.estadoMaquina = estadoMaquina;
            inValue.idTipoMaquina = idTipoMaquina;
            inValue.marca = marca;
            inValue.modelo = modelo;
            return ((SoftGestWA.MaquinaWS.Maquina)(this)).insertarMaquinaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse SoftGestWA.MaquinaWS.Maquina.obtenerPorIdMaquina(SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest request) {
            return base.Channel.obtenerPorIdMaquina(request);
        }
        
        public SoftGestWA.MaquinaWS.maquinaDTO obtenerPorIdMaquina(int idMaquina) {
            SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest inValue = new SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest();
            inValue.idMaquina = idMaquina;
            SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse retVal = ((SoftGestWA.MaquinaWS.Maquina)(this)).obtenerPorIdMaquina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse> SoftGestWA.MaquinaWS.Maquina.obtenerPorIdMaquinaAsync(SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest request) {
            return base.Channel.obtenerPorIdMaquinaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaquinaWS.obtenerPorIdMaquinaResponse> obtenerPorIdMaquinaAsync(int idMaquina) {
            SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest inValue = new SoftGestWA.MaquinaWS.obtenerPorIdMaquinaRequest();
            inValue.idMaquina = idMaquina;
            return ((SoftGestWA.MaquinaWS.Maquina)(this)).obtenerPorIdMaquinaAsync(inValue);
        }
    }
}
