//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGestWA.MaterialWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softgest.pucp.edu.pe/", ConfigurationName="MaterialWS.Material")]
    public interface Material {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/modificarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/modificarMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaterialWS.modificarMaterialResponse modificarMaterial(SoftGestWA.MaterialWS.modificarMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/modificarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/modificarMaterialResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.modificarMaterialResponse> modificarMaterialAsync(SoftGestWA.MaterialWS.modificarMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/insertarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/insertarMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaterialWS.insertarMaterialResponse insertarMaterial(SoftGestWA.MaterialWS.insertarMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/insertarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/insertarMaterialResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.insertarMaterialResponse> insertarMaterialAsync(SoftGestWA.MaterialWS.insertarMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/eliminarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/eliminarMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaterialWS.eliminarMaterialResponse eliminarMaterial(SoftGestWA.MaterialWS.eliminarMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/eliminarMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/eliminarMaterialResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.eliminarMaterialResponse> eliminarMaterialAsync(SoftGestWA.MaterialWS.eliminarMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/obtenerPorIdMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/obtenerPorIdMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse obtenerPorIdMaterial(SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/obtenerPorIdMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/obtenerPorIdMaterialResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse> obtenerPorIdMaterialAsync(SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/listarTodosMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/listarTodosMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftGestWA.MaterialWS.listarTodosMaterialResponse listarTodosMaterial(SoftGestWA.MaterialWS.listarTodosMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softgest.pucp.edu.pe/Material/listarTodosMaterialRequest", ReplyAction="http://services.softgest.pucp.edu.pe/Material/listarTodosMaterialResponse")]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.listarTodosMaterialResponse> listarTodosMaterialAsync(SoftGestWA.MaterialWS.listarTodosMaterialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class tipoMaterialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoMaterialField;
        
        private bool idTipoMaterialFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoMaterial {
            get {
                return this.idTipoMaterialField;
            }
            set {
                this.idTipoMaterialField = value;
                this.RaisePropertyChanged("idTipoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMaterialSpecified {
            get {
                return this.idTipoMaterialFieldSpecified;
            }
            set {
                this.idTipoMaterialFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softgest.pucp.edu.pe/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private int idMaterialField;
        
        private bool idMaterialFieldSpecified;
        
        private string marcaField;
        
        private string modeloField;
        
        private string nombreField;
        
        private tipoMaterialDTO tipoMaterialDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMaterial {
            get {
                return this.idMaterialField;
            }
            set {
                this.idMaterialField = value;
                this.RaisePropertyChanged("idMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMaterialSpecified {
            get {
                return this.idMaterialFieldSpecified;
            }
            set {
                this.idMaterialFieldSpecified = value;
                this.RaisePropertyChanged("idMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoMaterialDTO tipoMaterialDTO {
            get {
                return this.tipoMaterialDTOField;
            }
            set {
                this.tipoMaterialDTOField = value;
                this.RaisePropertyChanged("tipoMaterialDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterial", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaterialWS.date fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaterial;
        
        public modificarMaterialRequest() {
        }
        
        public modificarMaterialRequest(int idMaterial, string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            this.idMaterial = idMaterial;
            this.nombre = nombre;
            this.fechaVencimiento = fechaVencimiento;
            this.marca = marca;
            this.modelo = modelo;
            this.idTipoMaterial = idTipoMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterialResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMaterialResponse() {
        }
        
        public modificarMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterial", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaterialWS.date fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoMaterial;
        
        public insertarMaterialRequest() {
        }
        
        public insertarMaterialRequest(string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            this.nombre = nombre;
            this.fechaVencimiento = fechaVencimiento;
            this.marca = marca;
            this.modelo = modelo;
            this.idTipoMaterial = idTipoMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterialResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMaterialResponse() {
        }
        
        public insertarMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaterial", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public eliminarMaterialRequest() {
        }
        
        public eliminarMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaterialResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMaterialResponse() {
        }
        
        public eliminarMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMaterial", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public obtenerPorIdMaterialRequest() {
        }
        
        public obtenerPorIdMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMaterialResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaterialWS.materialDTO @return;
        
        public obtenerPorIdMaterialResponse() {
        }
        
        public obtenerPorIdMaterialResponse(SoftGestWA.MaterialWS.materialDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMaterial", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMaterialRequest {
        
        public listarTodosMaterialRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMaterialResponse", WrapperNamespace="http://services.softgest.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softgest.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftGestWA.MaterialWS.materialDTO[] @return;
        
        public listarTodosMaterialResponse() {
        }
        
        public listarTodosMaterialResponse(SoftGestWA.MaterialWS.materialDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaterialChannel : SoftGestWA.MaterialWS.Material, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialClient : System.ServiceModel.ClientBase<SoftGestWA.MaterialWS.Material>, SoftGestWA.MaterialWS.Material {
        
        public MaterialClient() {
        }
        
        public MaterialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaterialWS.modificarMaterialResponse SoftGestWA.MaterialWS.Material.modificarMaterial(SoftGestWA.MaterialWS.modificarMaterialRequest request) {
            return base.Channel.modificarMaterial(request);
        }
        
        public int modificarMaterial(int idMaterial, string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            SoftGestWA.MaterialWS.modificarMaterialRequest inValue = new SoftGestWA.MaterialWS.modificarMaterialRequest();
            inValue.idMaterial = idMaterial;
            inValue.nombre = nombre;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.idTipoMaterial = idTipoMaterial;
            SoftGestWA.MaterialWS.modificarMaterialResponse retVal = ((SoftGestWA.MaterialWS.Material)(this)).modificarMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.modificarMaterialResponse> SoftGestWA.MaterialWS.Material.modificarMaterialAsync(SoftGestWA.MaterialWS.modificarMaterialRequest request) {
            return base.Channel.modificarMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaterialWS.modificarMaterialResponse> modificarMaterialAsync(int idMaterial, string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            SoftGestWA.MaterialWS.modificarMaterialRequest inValue = new SoftGestWA.MaterialWS.modificarMaterialRequest();
            inValue.idMaterial = idMaterial;
            inValue.nombre = nombre;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.idTipoMaterial = idTipoMaterial;
            return ((SoftGestWA.MaterialWS.Material)(this)).modificarMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaterialWS.insertarMaterialResponse SoftGestWA.MaterialWS.Material.insertarMaterial(SoftGestWA.MaterialWS.insertarMaterialRequest request) {
            return base.Channel.insertarMaterial(request);
        }
        
        public int insertarMaterial(string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            SoftGestWA.MaterialWS.insertarMaterialRequest inValue = new SoftGestWA.MaterialWS.insertarMaterialRequest();
            inValue.nombre = nombre;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.idTipoMaterial = idTipoMaterial;
            SoftGestWA.MaterialWS.insertarMaterialResponse retVal = ((SoftGestWA.MaterialWS.Material)(this)).insertarMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.insertarMaterialResponse> SoftGestWA.MaterialWS.Material.insertarMaterialAsync(SoftGestWA.MaterialWS.insertarMaterialRequest request) {
            return base.Channel.insertarMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaterialWS.insertarMaterialResponse> insertarMaterialAsync(string nombre, SoftGestWA.MaterialWS.date fechaVencimiento, string marca, string modelo, int idTipoMaterial) {
            SoftGestWA.MaterialWS.insertarMaterialRequest inValue = new SoftGestWA.MaterialWS.insertarMaterialRequest();
            inValue.nombre = nombre;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.idTipoMaterial = idTipoMaterial;
            return ((SoftGestWA.MaterialWS.Material)(this)).insertarMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaterialWS.eliminarMaterialResponse SoftGestWA.MaterialWS.Material.eliminarMaterial(SoftGestWA.MaterialWS.eliminarMaterialRequest request) {
            return base.Channel.eliminarMaterial(request);
        }
        
        public int eliminarMaterial(int idMaterial) {
            SoftGestWA.MaterialWS.eliminarMaterialRequest inValue = new SoftGestWA.MaterialWS.eliminarMaterialRequest();
            inValue.idMaterial = idMaterial;
            SoftGestWA.MaterialWS.eliminarMaterialResponse retVal = ((SoftGestWA.MaterialWS.Material)(this)).eliminarMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.eliminarMaterialResponse> SoftGestWA.MaterialWS.Material.eliminarMaterialAsync(SoftGestWA.MaterialWS.eliminarMaterialRequest request) {
            return base.Channel.eliminarMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaterialWS.eliminarMaterialResponse> eliminarMaterialAsync(int idMaterial) {
            SoftGestWA.MaterialWS.eliminarMaterialRequest inValue = new SoftGestWA.MaterialWS.eliminarMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((SoftGestWA.MaterialWS.Material)(this)).eliminarMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse SoftGestWA.MaterialWS.Material.obtenerPorIdMaterial(SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest request) {
            return base.Channel.obtenerPorIdMaterial(request);
        }
        
        public SoftGestWA.MaterialWS.materialDTO obtenerPorIdMaterial(int idMaterial) {
            SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest inValue = new SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest();
            inValue.idMaterial = idMaterial;
            SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse retVal = ((SoftGestWA.MaterialWS.Material)(this)).obtenerPorIdMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse> SoftGestWA.MaterialWS.Material.obtenerPorIdMaterialAsync(SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest request) {
            return base.Channel.obtenerPorIdMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaterialWS.obtenerPorIdMaterialResponse> obtenerPorIdMaterialAsync(int idMaterial) {
            SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest inValue = new SoftGestWA.MaterialWS.obtenerPorIdMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((SoftGestWA.MaterialWS.Material)(this)).obtenerPorIdMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftGestWA.MaterialWS.listarTodosMaterialResponse SoftGestWA.MaterialWS.Material.listarTodosMaterial(SoftGestWA.MaterialWS.listarTodosMaterialRequest request) {
            return base.Channel.listarTodosMaterial(request);
        }
        
        public SoftGestWA.MaterialWS.materialDTO[] listarTodosMaterial() {
            SoftGestWA.MaterialWS.listarTodosMaterialRequest inValue = new SoftGestWA.MaterialWS.listarTodosMaterialRequest();
            SoftGestWA.MaterialWS.listarTodosMaterialResponse retVal = ((SoftGestWA.MaterialWS.Material)(this)).listarTodosMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftGestWA.MaterialWS.listarTodosMaterialResponse> SoftGestWA.MaterialWS.Material.listarTodosMaterialAsync(SoftGestWA.MaterialWS.listarTodosMaterialRequest request) {
            return base.Channel.listarTodosMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftGestWA.MaterialWS.listarTodosMaterialResponse> listarTodosMaterialAsync() {
            SoftGestWA.MaterialWS.listarTodosMaterialRequest inValue = new SoftGestWA.MaterialWS.listarTodosMaterialRequest();
            return ((SoftGestWA.MaterialWS.Material)(this)).listarTodosMaterialAsync(inValue);
        }
    }
}
